# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: InsideJS
email: zzoonis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 이 블로그는 "http://nodejs-kr.org/insidejs" 의 블로그를 migration 하였습니다.
 migration 중에 깨진 이미지나 소스코드는 추후 개선 예정입니다.
 양해 부탁드립니다.
baseurl: /insidejs # the subpath of your site, e.g. /blog
url: "http://zzoon.github.io/insidejs" # the base hostname & protocol for your site
twitter_username: zzoon
github_username:  zzoon

# Build settings
markdown: kramdown
